/**
 * DocFlow tool catalog — mirrors the Node backend's Stirling registry
 * (docflow/backend/src/services/tools.js) field-for-field.
 *
 * Every `id` here is a tool id the backend knows. The `options` array drives
 * the converter UI: each entry becomes one form control, and its `key` is the
 * multipart field name the backend validates. Do not rename keys — the
 * backend's `fields()` mappers read exactly these.
 *
 * Default values and clamps were verified against Stirling 2.14.3 (see the
 * comments in the backend registry) — don't "fix" ranges without re-testing.
 */

export type OptionField =
  | {
      type: 'text';
      key: string;
      label: string;
      placeholder?: string;
      required?: boolean;
      help?: string;
    }
  | { type: 'password'; key: string; label: string; required?: boolean; help?: string }
  | {
      type: 'select';
      key: string;
      label: string;
      choices: { value: string; label: string }[];
      help?: string;
      default?: string;
    }
  | {
      type: 'number';
      key: string;
      label: string;
      min: number;
      max: number;
      step?: number;
      help?: string;
      default?: string;
    }
  | { type: 'checkbox'; key: string; label: string; help?: string; default?: string }
  | { type: 'color'; key: string; label: string; help?: string; default?: string };

export interface Tool {
  id: string;
  title: string;
  description: string;
  /** Short input/output badges, e.g. "PDF" → "DOCX". */
  from: string;
  to: string;
  /** Icon key into ICONS below. */
  icon: string;
  color: string;
  tint: string;
  category: 'convert' | 'organize' | 'optimize' | 'security';
  multiFile: boolean;
  minFiles: number;
  /** Input extensions the picker offers. */
  accept: string[];
  options: OptionField[];
  popular?: boolean;
  steps: [string, string, string];
}

export const CATEGORIES: { id: Tool['category']; label: string }[] = [
  { id: 'convert', label: 'Convert' },
  { id: 'organize', label: 'Organize' },
  { id: 'optimize', label: 'Optimize & Edit' },
  { id: 'security', label: 'Secure' },
];

// Palette + tints kept in one place so new tools stay on-brand.
const BLUE = '#4B68FF';
const BLUE_TINT = '#EEF0FF';
const AMBER = '#FCA82F';
const AMBER_TINT = '#FFF7EB';
const CORAL = '#FA5B5D';
const CORAL_TINT = '#FFF1F1';
const VIOLET = '#7B5EFF';
const VIOLET_TINT = '#F3F3FF';
const GREEN = '#39D9A1';
const GREEN_TINT = '#DAF4EE';
const BROWN = '#A9715E';
const BROWN_TINT = '#F8F4F2';

export const TOOLS: Tool[] = [
  /* ------------------------------ Convert ------------------------------ */
  {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Convert PDF documents to fully editable .docx files.',
    from: 'PDF',
    to: 'DOCX',
    icon: 'fileText',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    popular: true,
    steps: [
      'Select or drop a PDF file above.',
      'Press Convert — the document is rebuilt as .docx on our servers.',
      'Download the result and keep editing in Word.',
    ],
  },
  {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Turn Word documents into universal, shareable PDFs.',
    from: 'DOCX',
    to: 'PDF',
    icon: 'fileType',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['docx', 'doc', 'odt', 'rtf', 'txt'],
    options: [],
    popular: true,
    steps: [
      'Select a Word document (.docx, .doc, .odt, .rtf or .txt).',
      'Press Convert to produce a clean, print-ready PDF.',
      'Download your PDF — formatting preserved.',
    ],
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Extract tables and data from PDFs into CSV spreadsheets.',
    from: 'PDF',
    to: 'CSV',
    icon: 'table',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'text',
        key: 'pages',
        label: 'Pages',
        placeholder: 'all — or e.g. 1,3,5-9',
        help: 'Which pages to scan for tables. Leave as "all" for the whole document.',
      },
    ],
    steps: [
      'Upload a PDF that contains tables.',
      'Press Convert — detected tables are extracted as CSV.',
      'Download and open the data in Excel or Sheets.',
    ],
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Convert spreadsheets into clean, shareable PDFs.',
    from: 'XLSX',
    to: 'PDF',
    icon: 'sheet',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['xlsx', 'xls', 'ods', 'csv'],
    options: [],
    steps: [
      'Select a spreadsheet (.xlsx, .xls, .ods or .csv).',
      'Press Convert to render it as a PDF document.',
      'Download the PDF, ready to share.',
    ],
  },
  {
    id: 'pdf-to-ppt',
    title: 'PDF to PowerPoint',
    description: 'Turn PDF pages into an editable slide deck.',
    from: 'PDF',
    to: 'PPTX',
    icon: 'presentation',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'format',
        label: 'Presentation format',
        choices: [
          { value: 'pptx', label: 'PPTX — PowerPoint' },
          { value: 'ppt', label: 'PPT — legacy PowerPoint' },
          { value: 'odp', label: 'ODP — OpenDocument' },
        ],
        default: 'pptx',
      },
    ],
    steps: [
      'Upload the PDF you want as slides.',
      'Pick your presentation format.',
      'Download the deck and present or edit it.',
    ],
  },
  {
    id: 'ppt-to-pdf',
    title: 'PowerPoint to PDF',
    description: 'Convert slide decks into fixed-layout PDFs.',
    from: 'PPTX',
    to: 'PDF',
    icon: 'presentation',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pptx', 'ppt', 'odp'],
    options: [],
    steps: [
      'Select a presentation (.pptx, .ppt or .odp).',
      'Press Convert — each slide becomes one PDF page.',
      'Download the PDF, perfect for sharing.',
    ],
  },
  {
    id: 'pdf-to-text',
    title: 'PDF to Text',
    description: 'Extract raw text from a PDF as .txt or .rtf.',
    from: 'PDF',
    to: 'TXT',
    icon: 'type',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'format',
        label: 'Text format',
        choices: [
          { value: 'txt', label: 'TXT — plain text' },
          { value: 'rtf', label: 'RTF — keeps basic formatting' },
        ],
        default: 'txt',
      },
    ],
    steps: [
      'Upload a text-based PDF (not a scan).',
      'Choose plain text or RTF.',
      'Download the extracted text.',
    ],
  },
  {
    id: 'pdf-to-xml',
    title: 'PDF to XML',
    description: 'Convert PDF structure and content into XML.',
    from: 'PDF',
    to: 'XML',
    icon: 'code',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF to convert.',
      'Press Convert — the document is mapped to XML.',
      'Download the XML file.',
    ],
  },
  {
    id: 'pdf-to-html',
    title: 'PDF to HTML',
    description: 'Rebuild a PDF as an HTML page with its images and styling.',
    from: 'PDF',
    to: 'ZIP',
    icon: 'globe',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF you want on the web.',
      'Press Convert — the layout is rebuilt as HTML plus assets.',
      'Download the ZIP and open index.html anywhere.',
    ],
  },
  {
    id: 'pdf-to-epub',
    title: 'PDF to EPUB',
    description: 'Turn a PDF into a reflowable EPUB e-book.',
    from: 'PDF',
    to: 'EPUB',
    icon: 'book',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'checkbox',
        key: 'detectChapters',
        label: 'Auto-detect chapters',
        default: 'true',
      },
      {
        type: 'select',
        key: 'device',
        label: 'Optimize for',
        choices: [
          { value: 'tablet', label: 'Tablets & phones' },
          { value: 'kindle', label: 'Kindle e-ink' },
        ],
        default: 'tablet',
      },
    ],
    steps: [
      'Upload the PDF you want to read as an e-book.',
      'Pick the target device and chapter detection.',
      'Download the EPUB and load it onto your reader.',
    ],
  },
  {
    id: 'pdf-to-pdfa',
    title: 'PDF to PDF/A',
    description: 'Convert to PDF/A — the archival standard for long-term storage.',
    from: 'PDF',
    to: 'PDF/A',
    icon: 'fileCheck',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF to archive.',
      'Press Convert — the file is normalized to PDF/A.',
      'Download the archival-safe PDF.',
    ],
  },
  {
    id: 'pdf-to-xlsx',
    title: 'PDF to XLSX',
    description: 'Extract PDF content into Excel .xlsx spreadsheets.',
    from: 'PDF',
    to: 'XLSX',
    icon: 'table',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'text',
        key: 'pages',
        label: 'Pages',
        placeholder: 'all — or e.g. 1,3,5-9',
        help: 'Which pages to extract. Leave as "all" for the whole document.',
      },
    ],
    steps: [
      'Upload the PDF with the data you need.',
      'Optionally narrow the page range.',
      'Download the .xlsx and keep working in Excel.',
    ],
  },
  {
    id: 'image-to-pdf',
    title: 'JPG to PDF',
    description: 'Turn one or many images into a single PDF document.',
    from: 'JPG/PNG',
    to: 'PDF',
    icon: 'image',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'convert',
    multiFile: true,
    minFiles: 1,
    accept: ['jpg', 'jpeg', 'png', 'webp', 'heic'],
    options: [
      {
        type: 'select',
        key: 'fit',
        label: 'Page fit',
        choices: [
          { value: 'fitDocumentToImage', label: 'Page matches image size' },
          { value: 'fitImageToDocument', label: 'Image fits standard page' },
          { value: 'maintainAspectRatio', label: 'Maintain aspect ratio' },
        ],
        default: 'fitDocumentToImage',
      },
      {
        type: 'checkbox',
        key: 'autoRotate',
        label: 'Auto-rotate landscape images',
        default: 'true',
      },
    ],
    popular: true,
    steps: [
      'Add your images (JPG, PNG, WebP or HEIC).',
      'Pick how images should fit the page.',
      'Download one PDF with all images inside.',
    ],
  },
  {
    id: 'pdf-to-image',
    title: 'PDF to JPG',
    description: 'Render PDF pages as PNG or JPG images.',
    from: 'PDF',
    to: 'PNG/JPG',
    icon: 'imageOut',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'text', key: 'pages', label: 'Pages', placeholder: 'all' },
      {
        type: 'select',
        key: 'format',
        label: 'Image format',
        choices: [
          { value: 'png', label: 'PNG — lossless' },
          { value: 'jpeg', label: 'JPG — smaller files' },
        ],
        default: 'png',
      },
      {
        type: 'checkbox',
        key: 'singlePage',
        label: 'Stitch into one image',
        help: 'Off: one image per page (delivered as ZIP). On: all pages combined into one tall image.',
        default: 'false',
      },
      { type: 'number', key: 'dpi', label: 'Resolution (DPI)', min: 72, max: 600, step: 1, default: '300' },
    ],
    steps: [
      'Upload a PDF.',
      'Choose format, pages and resolution.',
      'Download your images — a ZIP when there is one per page.',
    ],
  },
  {
    id: 'markdown-to-pdf',
    title: 'Markdown to PDF',
    description: 'Render Markdown files as formatted PDF documents.',
    from: 'MD',
    to: 'PDF',
    icon: 'code',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['md', 'markdown', 'txt'],
    options: [],
    steps: [
      'Upload your .md file.',
      'Press Convert — headings, lists and links are typeset.',
      'Download the styled PDF.',
    ],
  },
  {
    id: 'html-to-pdf',
    title: 'HTML to PDF',
    description: 'Turn an HTML page (or zipped site) into a PDF.',
    from: 'HTML',
    to: 'PDF',
    icon: 'globe',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['html', 'htm', 'zip'],
    options: [],
    steps: [
      'Upload an .html file, or a .zip of the page and its assets.',
      'Press Convert — the page is rendered exactly as in a browser.',
      'Download the PDF.',
    ],
  },
  {
    id: 'svg-to-pdf',
    title: 'SVG to PDF',
    description: 'Convert vector graphics into PDF, singly or combined.',
    from: 'SVG',
    to: 'PDF',
    icon: 'penTool',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'convert',
    multiFile: true,
    minFiles: 1,
    accept: ['svg'],
    options: [
      {
        type: 'checkbox',
        key: 'combine',
        label: 'Combine all SVGs into one PDF',
        default: 'true',
      },
    ],
    steps: [
      'Add one or more .svg files.',
      'Choose whether to merge them into a single PDF.',
      'Download the vector-sharp result.',
    ],
  },
  {
    id: 'ebook-to-pdf',
    title: 'EPUB to PDF',
    description: 'Convert e-books (EPUB, MOBI, AZW3) into PDFs.',
    from: 'EPUB',
    to: 'PDF',
    icon: 'book',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['epub', 'mobi', 'azw3'],
    options: [
      { type: 'checkbox', key: 'includeToc', label: 'Include table of contents', default: 'false' },
      { type: 'checkbox', key: 'includePageNumbers', label: 'Add page numbers', default: 'false' },
    ],
    steps: [
      'Upload your e-book (.epub, .mobi or .azw3).',
      'Optionally add a table of contents and page numbers.',
      'Download the PDF version.',
    ],
  },
  {
    id: 'cbz-to-pdf',
    title: 'CBZ to PDF',
    description: 'Turn comic book archives (CBZ) into PDFs.',
    from: 'CBZ',
    to: 'PDF',
    icon: 'archive',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['cbz'],
    options: [],
    steps: [
      'Upload your .cbz comic archive.',
      'Press Convert — each image becomes a page.',
      'Download the PDF comic.',
    ],
  },
  {
    id: 'cbr-to-pdf',
    title: 'CBR to PDF',
    description: 'Turn comic book archives (CBR) into PDFs.',
    from: 'CBR',
    to: 'PDF',
    icon: 'archive',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['cbr'],
    options: [],
    steps: [
      'Upload your .cbr comic archive.',
      'Press Convert — each image becomes a page.',
      'Download the PDF comic.',
    ],
  },
  {
    id: 'pdf-to-cbz',
    title: 'PDF to CBZ',
    description: 'Render PDF pages as a comic book archive (CBZ).',
    from: 'PDF',
    to: 'CBZ',
    icon: 'archive',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'number', key: 'dpi', label: 'Resolution (DPI)', min: 72, max: 600, step: 1, default: '150' },
    ],
    steps: [
      'Upload the PDF.',
      'Pick the resolution for the page images.',
      'Download the .cbz archive.',
    ],
  },
  {
    id: 'pdf-to-cbr',
    title: 'PDF to CBR',
    description: 'Render PDF pages as a comic book archive (CBR).',
    from: 'PDF',
    to: 'CBR',
    icon: 'archive',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'convert',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'number', key: 'dpi', label: 'Resolution (DPI)', min: 72, max: 600, step: 1, default: '150' },
    ],
    steps: [
      'Upload the PDF.',
      'Pick the resolution for the page images.',
      'Download the .cbr archive.',
    ],
  },

  /* ------------------------------ Organize ----------------------------- */
  {
    id: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine multiple PDFs into a single document, in your order.',
    from: 'PDF+PDF',
    to: 'PDF',
    icon: 'combine',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'organize',
    multiFile: true,
    minFiles: 2,
    accept: ['pdf'],
    options: [],
    popular: true,
    steps: [
      'Add at least two PDFs, then drag or use the arrows to order them.',
      'Press Merge — files are joined in exactly the order shown.',
      'Download one combined PDF.',
    ],
  },
  {
    id: 'split-pdf',
    title: 'Split PDF',
    description: 'Extract specific pages or ranges from any PDF.',
    from: 'PDF',
    to: 'ZIP',
    icon: 'scissors',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'text',
        key: 'pages',
        label: 'Pages to extract',
        placeholder: 'e.g. 1,3,5-9',
        required: true,
        help: 'Comma-separated pages and ranges, e.g. "1,3,5-9". Each range becomes its own PDF.',
      },
    ],
    steps: [
      'Upload the PDF you want to split.',
      'Type the pages to extract, e.g. 1,3,5-9.',
      'Download a ZIP with one PDF per page range.',
    ],
  },
  {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate every page 90, 180 or 270 degrees.',
    from: 'PDF',
    to: 'PDF',
    icon: 'rotate',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'angle',
        label: 'Rotation',
        choices: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '90° counter-clockwise' },
        ],
        default: '90',
      },
    ],
    steps: [
      'Upload the PDF with sideways pages.',
      'Choose how far to rotate.',
      'Download the straightened PDF.',
    ],
  },
  {
    id: 'remove-pages',
    title: 'Remove Pages',
    description: 'Delete unwanted pages from a PDF.',
    from: 'PDF',
    to: 'PDF',
    icon: 'fileMinus',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'text',
        key: 'pages',
        label: 'Pages to remove',
        placeholder: 'e.g. 2,5-7',
        required: true,
        help: 'Comma-separated pages and ranges to delete. Everything else is kept.',
      },
    ],
    steps: [
      'Upload the PDF to trim.',
      'Type the pages to remove, e.g. 2,5-7.',
      'Download the slimmed-down PDF.',
    ],
  },
  {
    id: 'rearrange-pages',
    title: 'Reorganize Pages',
    description: 'Reorder pages — reverse, booklet sort, or a custom order.',
    from: 'PDF',
    to: 'PDF',
    icon: 'shuffle',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'mode',
        label: 'Mode',
        choices: [
          { value: 'REVERSE_ORDER', label: 'Reverse order' },
          { value: 'DUPLEX_SORT', label: 'Duplex sort' },
          { value: 'BOOKLET_SORT', label: 'Booklet sort' },
          { value: 'ODD_EVEN_SPLIT', label: 'Odd/even split' },
          { value: 'REMOVE_FIRST', label: 'Remove first page' },
          { value: 'REMOVE_LAST', label: 'Remove last page' },
          { value: 'REMOVE_FIRST_AND_LAST', label: 'Remove first & last page' },
          { value: 'DUPLICATE', label: 'Duplicate pages' },
          { value: 'CUSTOM', label: 'Custom order' },
        ],
        default: 'REVERSE_ORDER',
      },
      {
        type: 'text',
        key: 'pages',
        label: 'Custom order',
        placeholder: 'e.g. 3,1,2',
        help: 'Only used with "Custom order" — the new page sequence.',
      },
    ],
    steps: [
      'Upload the PDF to reorder.',
      'Pick a mode — or a fully custom page order.',
      'Download the reorganized PDF.',
    ],
  },
  {
    id: 'pdf-to-single-page',
    title: 'PDF to Single Page',
    description: 'Merge all pages of a PDF into one long page.',
    from: 'PDF',
    to: 'PDF',
    icon: 'square',
    color: BLUE,
    tint: BLUE_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF.',
      'Press Convert — all pages stack into one continuous page.',
      'Download the single-page PDF.',
    ],
  },
  {
    id: 'split-by-sections',
    title: 'Split by Sections',
    description: 'Cut pages into a grid of sections (e.g. 2×2).',
    from: 'PDF',
    to: 'ZIP',
    icon: 'sections',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'number', key: 'horizontal', label: 'Horizontal cuts', min: 1, max: 10, default: '1' },
      { type: 'number', key: 'vertical', label: 'Vertical cuts', min: 1, max: 10, default: '1' },
      { type: 'checkbox', key: 'merge', label: 'Merge into one PDF', default: 'false' },
    ],
    steps: [
      'Upload the PDF to slice.',
      'Set how many horizontal and vertical cuts to make.',
      'Download the sections — ZIP, or one merged PDF.',
    ],
  },
  {
    id: 'split-by-size',
    title: 'Split by Size or Count',
    description: 'Split a PDF by file size, page count, or number of parts.',
    from: 'PDF',
    to: 'ZIP',
    icon: 'weight',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'splitType',
        label: 'Split by',
        choices: [
          { value: '0', label: 'File size' },
          { value: '1', label: 'Page count' },
          { value: '2', label: 'Number of documents' },
        ],
        default: '0',
      },
      {
        type: 'text',
        key: 'splitValue',
        label: 'Value',
        placeholder: 'e.g. 10MB or 5',
        required: true,
        help: 'Size like "10MB" when splitting by size; a number of pages or parts otherwise.',
      },
    ],
    steps: [
      'Upload the PDF to divide.',
      'Choose the split rule and value, e.g. "10MB" or "5".',
      'Download the ZIP of parts.',
    ],
  },
  {
    id: 'split-by-chapters',
    title: 'Split by Chapters',
    description: 'Split a PDF at its bookmarks into chapter files.',
    from: 'PDF',
    to: 'ZIP',
    icon: 'bookmark',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'number', key: 'bookmarkLevel', label: 'Bookmark level', min: 1, max: 5, default: '1', help: '1 = top-level bookmarks.' },
      { type: 'checkbox', key: 'includeMetadata', label: 'Keep metadata in parts', default: 'true' },
    ],
    steps: [
      'Upload a PDF that has bookmarks.',
      'Pick which bookmark level marks chapter breaks.',
      'Download a ZIP with one PDF per chapter.',
    ],
  },
  {
    id: 'overlay-pdfs',
    title: 'Overlay PDFs',
    description: 'Stack PDFs on top of each other — fill forms, add layers.',
    from: 'PDF+PDF',
    to: 'PDF',
    icon: 'layers',
    color: BLUE,
    tint: BLUE_TINT,
    category: 'organize',
    multiFile: true,
    minFiles: 2,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'mode',
        label: 'Overlay mode',
        choices: [
          { value: 'sequential', label: 'Sequential — base page 1 gets overlay 1, page 2 gets overlay 2…' },
          { value: 'interleaved', label: 'Interleaved — overlays cycle across pages' },
        ],
        default: 'sequential',
      },
      {
        type: 'select',
        key: 'position',
        label: 'Overlay position',
        choices: [
          { value: 'foreground', label: 'On top of the base' },
          { value: 'background', label: 'Behind the base' },
        ],
        default: 'foreground',
      },
    ],
    steps: [
      'Upload the base PDF first, then one or more overlays.',
      'Choose how overlays apply across pages.',
      'Download the combined PDF.',
    ],
  },
  {
    id: 'multi-page-layout',
    title: 'N-up Layout',
    description: 'Place multiple PDF pages on one sheet (2-up, 4-up, …).',
    from: 'PDF',
    to: 'PDF',
    icon: 'grid',
    color: BLUE,
    tint: BLUE_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'pagesPerSheet',
        label: 'Pages per sheet',
        choices: [
          { value: '2', label: '2 pages' },
          { value: '4', label: '4 pages (2×2)' },
          { value: '9', label: '9 pages (3×3)' },
          { value: '16', label: '16 pages (4×4)' },
        ],
        default: '2',
      },
      { type: 'checkbox', key: 'addBorder', label: 'Add borders around pages', default: 'false' },
    ],
    steps: [
      'Upload the PDF.',
      'Choose how many pages fit on each sheet.',
      'Download the compact PDF — great for handouts.',
    ],
  },
  {
    id: 'scale-pages',
    title: 'Scale Pages',
    description: 'Resize pages to a standard paper size and scale content.',
    from: 'PDF',
    to: 'PDF',
    icon: 'maximize',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'pageSize',
        label: 'Paper size',
        choices: [
          { value: 'A4', label: 'A4' },
          { value: 'A3', label: 'A3' },
          { value: 'LETTER', label: 'Letter' },
          { value: 'LEGAL', label: 'Legal' },
        ],
        default: 'A4',
      },
      {
        type: 'select',
        key: 'orientation',
        label: 'Orientation',
        choices: [
          { value: 'portrait', label: 'Portrait' },
          { value: 'landscape', label: 'Landscape' },
        ],
        default: 'portrait',
      },
      { type: 'number', key: 'scale', label: 'Content scale', min: 0.1, max: 4, step: 0.1, default: '1' },
    ],
    steps: [
      'Upload the PDF to resize.',
      'Pick the target paper size and content scale.',
      'Download the resized PDF.',
    ],
  },
  {
    id: 'crop-pdf',
    title: 'Crop PDF',
    description: 'Crop pages to a region — manually or fully automatic.',
    from: 'PDF',
    to: 'PDF',
    icon: 'crop',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'checkbox', key: 'autoCrop', label: 'Auto-detect content', default: 'false', help: 'Ignores the numbers below and crops to the detected content.' },
      { type: 'number', key: 'x', label: 'X (pt)', min: -2000, max: 2000, default: '0' },
      { type: 'number', key: 'y', label: 'Y (pt)', min: -2000, max: 2000, default: '0' },
      { type: 'number', key: 'width', label: 'Width (pt)', min: 1, max: 5000, default: '595' },
      { type: 'number', key: 'height', label: 'Height (pt)', min: 1, max: 5000, default: '842' },
    ],
    steps: [
      'Upload the PDF to crop.',
      'Set the crop box (or let auto-detect do it).',
      'Download the cropped PDF.',
    ],
  },
  {
    id: 'auto-split-pdf',
    title: 'Auto Split by Scanner',
    description: 'Split a scanned stack where QR separator sheets appear.',
    from: 'PDF',
    to: 'ZIP',
    icon: 'scan',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'checkbox', key: 'duplex', label: 'Duplex scan (backs have no QR)', default: 'false' },
    ],
    steps: [
      'Upload a scan that contains QR separator sheets.',
      'Tick duplex if your scanner captured page backs.',
      'Download a ZIP with one PDF per separated document.',
    ],
  },
  {
    id: 'remove-images',
    title: 'Remove Images',
    description: 'Strip all images from a PDF, keeping the text.',
    from: 'PDF',
    to: 'PDF',
    icon: 'imageOff',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF.',
      'Press Convert — images are stripped, text stays.',
      'Download the lightweight, text-only PDF.',
    ],
  },
  {
    id: 'booklet-imposition',
    title: 'Booklet',
    description: 'Reorder pages for booklet printing and folding.',
    from: 'PDF',
    to: 'PDF',
    icon: 'bookOpen',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'spine',
        label: 'Spine side',
        choices: [
          { value: 'left', label: 'Left (Western binding)' },
          { value: 'right', label: 'Right (right-to-left binding)' },
        ],
        default: 'left',
      },
      { type: 'checkbox', key: 'doubleSided', label: 'Double-sided printer', default: 'true' },
      { type: 'checkbox', key: 'addBorder', label: 'Add page borders', default: 'false' },
    ],
    steps: [
      'Upload the PDF to bind.',
      'Choose the spine side and printer type.',
      'Download the imposed booklet and print it.',
    ],
  },
  {
    id: 'poster-pdf',
    title: 'Poster Split',
    description: 'Split one page across multiple sheets for poster printing.',
    from: 'PDF',
    to: 'PDF',
    icon: 'printer',
    color: BLUE,
    tint: BLUE_TINT,
    category: 'organize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'pageSize',
        label: 'Sheet size',
        choices: [
          { value: 'A4', label: 'A4' },
          { value: 'A3', label: 'A3' },
          { value: 'A2', label: 'A2' },
          { value: 'A1', label: 'A1' },
          { value: 'A0', label: 'A0' },
          { value: 'LETTER', label: 'Letter' },
          { value: 'LEGAL', label: 'Legal' },
        ],
        default: 'A4',
      },
      { type: 'number', key: 'xFactor', label: 'Sheets across', min: 1, max: 10, default: '2' },
      { type: 'number', key: 'yFactor', label: 'Sheets down', min: 1, max: 10, default: '2' },
    ],
    steps: [
      'Upload the one-page poster PDF.',
      'Choose the sheet size and grid (e.g. 2×2).',
      'Download the multi-page PDF and print, trim, assemble.',
    ],
  },

  /* --------------------------- Optimize & Edit -------------------------- */
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Shrink PDF file size while keeping quality readable.',
    from: 'PDF',
    to: 'PDF',
    icon: 'minimize',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'level',
        label: 'Compression level',
        choices: [
          { value: 'low', label: 'Low — best quality' },
          { value: 'medium', label: 'Medium — balanced' },
          { value: 'high', label: 'High — smallest file' },
        ],
        default: 'low',
        help: 'High typically reaches 94–97% of the original size.',
      },
      {
        type: 'checkbox',
        key: 'grayscale',
        label: 'Convert to grayscale',
        default: 'false',
        help: 'Drops color information for extra savings.',
      },
    ],
    popular: true,
    steps: [
      'Upload the PDF you want to slim down.',
      'Choose a compression level (and grayscale if you like).',
      'Download the smaller PDF.',
    ],
  },
  {
    id: 'decompress-pdf',
    title: 'Decompress PDF',
    description: 'Remove compression from a PDF for editing tools.',
    from: 'PDF',
    to: 'PDF',
    icon: 'expand',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the compressed PDF.',
      'Press Convert — compressed streams are expanded.',
      'Download the editable PDF.',
    ],
  },
  {
    id: 'repair-pdf',
    title: 'Repair PDF',
    description: 'Try to recover a damaged or unreadable PDF.',
    from: 'PDF',
    to: 'PDF',
    icon: 'wrench',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the broken PDF.',
      'Press Convert — the structure is rebuilt where possible.',
      'Download the recovered PDF.',
    ],
  },
  {
    id: 'ocr-pdf',
    title: 'OCR PDF',
    description: 'Make scanned pages searchable with text recognition.',
    from: 'PDF',
    to: 'PDF',
    icon: 'scanText',
    color: BLUE,
    tint: BLUE_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'text', key: 'languages', label: 'Languages', placeholder: 'eng', help: 'Comma-separated language codes, e.g. "eng", "eng,deu".' },
      {
        type: 'select',
        key: 'ocrType',
        label: 'OCR mode',
        choices: [
          { value: 'skip-text', label: 'Skip pages that already have text' },
          { value: 'force-ocr', label: 'Force OCR on every page' },
        ],
        default: 'skip-text',
      },
      { type: 'checkbox', key: 'deskew', label: 'Straighten tilted scans', default: 'false' },
    ],
    steps: [
      'Upload the scanned PDF.',
      'Pick the languages in the document.',
      'Download the searchable PDF — text is now selectable.',
    ],
  },
  {
    id: 'flatten-pdf',
    title: 'Flatten PDF',
    description: 'Bake forms, layers and annotations into the page.',
    from: 'PDF',
    to: 'PDF',
    icon: 'flatten',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'checkbox', key: 'onlyForms', label: 'Only flatten form fields', default: 'false' },
      { type: 'number', key: 'dpi', label: 'Render DPI', min: 72, max: 600, default: '150' },
    ],
    steps: [
      'Upload the PDF with forms or annotations.',
      'Choose what to flatten.',
      'Download the flat PDF — nothing left to edit.',
    ],
  },
  {
    id: 'extract-images',
    title: 'Extract Images',
    description: 'Pull every embedded image out of a PDF.',
    from: 'PDF',
    to: 'ZIP',
    icon: 'image',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF.',
      'Press Extract — every image is pulled out at full quality.',
      'Download the ZIP of images.',
    ],
  },
  {
    id: 'extract-image-scans',
    title: 'Extract Scans',
    description: 'Detect and extract scanned photos from a PDF.',
    from: 'PDF',
    to: 'ZIP',
    icon: 'scan',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'number', key: 'angleThreshold', label: 'Angle threshold', min: 1, max: 90, default: '5' },
      { type: 'number', key: 'tolerance', label: 'Tolerance', min: 0, max: 100, default: '10' },
      { type: 'number', key: 'minArea', label: 'Min area', min: 100, max: 1000000, default: '8000' },
      { type: 'number', key: 'borderSize', label: 'Border (px)', min: 0, max: 50, default: '1' },
    ],
    steps: [
      'Upload the scanned PDF.',
      'Tune detection, or leave the defaults.',
      'Download the ZIP of detected scans.',
    ],
  },
  {
    id: 'remove-blank-pages',
    title: 'Remove Blank Pages',
    description: 'Detect and delete blank pages from scans.',
    from: 'PDF',
    to: 'PDF',
    icon: 'eraser',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'number', key: 'threshold', label: 'Darkness threshold', min: 1, max: 100, default: '10' },
      { type: 'number', key: 'whitePercent', label: 'White cutoff (%)', min: 0, max: 100, step: 0.1, default: '99.9', help: 'A page is "blank" when it is at least this white.' },
    ],
    steps: [
      'Upload the scanned PDF.',
      'Set how white a page must be to count as blank.',
      'Download the PDF without the empties.',
    ],
  },
  {
    id: 'auto-rename',
    title: 'Auto-Rename PDF',
    description: 'Rename the file from the title detected inside the PDF.',
    from: 'PDF',
    to: 'PDF',
    icon: 'sparkle',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the misnamed PDF.',
      'Press Convert — the first title text becomes the filename.',
      'Download the correctly named PDF.',
    ],
  },
  {
    id: 'add-stamp',
    title: 'Add Stamp',
    description: 'Stamp custom text anywhere on the page.',
    from: 'PDF',
    to: 'PDF',
    icon: 'stamp',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'text', key: 'stampText', label: 'Stamp text', placeholder: 'e.g. APPROVED', required: true },
      { type: 'color', key: 'color', label: 'Color', default: '#d3d3d3' },
      { type: 'number', key: 'size', label: 'Font size', min: 8, max: 96, default: '30' },
      { type: 'number', key: 'angle', label: 'Angle (°)', min: -90, max: 90, default: '0' },
      { type: 'number', key: 'opacity', label: 'Opacity', min: 0.05, max: 1, step: 0.05, default: '0.5' },
      {
        type: 'select',
        key: 'position',
        label: 'Position',
        choices: [
          { value: '1', label: 'Bottom left' },
          { value: '2', label: 'Bottom center' },
          { value: '3', label: 'Bottom right' },
          { value: '4', label: 'Middle left' },
          { value: '5', label: 'Center' },
          { value: '6', label: 'Middle right' },
          { value: '7', label: 'Top left' },
          { value: '8', label: 'Top center' },
          { value: '9', label: 'Top right' },
        ],
        default: '8',
      },
    ],
    steps: [
      'Upload the PDF to stamp.',
      'Type your text and place it on the page.',
      'Download the stamped PDF.',
    ],
  },
  {
    id: 'add-page-numbers',
    title: 'Add Page Numbers',
    description: 'Insert page numbers with custom format and position.',
    from: 'PDF',
    to: 'PDF',
    icon: 'hash',
    color: BLUE,
    tint: BLUE_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'position',
        label: 'Position',
        choices: [
          { value: '1', label: 'Top left' },
          { value: '2', label: 'Top center' },
          { value: '3', label: 'Top right' },
          { value: '4', label: 'Middle left' },
          { value: '5', label: 'Center' },
          { value: '6', label: 'Middle right' },
          { value: '7', label: 'Bottom left' },
          { value: '8', label: 'Bottom center' },
          { value: '9', label: 'Bottom right' },
        ],
        default: '8',
      },
      { type: 'number', key: 'startAt', label: 'Start numbering at', min: 0, max: 10000, default: '1' },
      { type: 'text', key: 'customText', label: 'Custom text', placeholder: 'e.g. Page {n} of {total}', help: 'Optional. "{n}" is the page number.' },
      { type: 'text', key: 'pages', label: 'Pages to number', placeholder: 'all' },
      { type: 'number', key: 'size', label: 'Font size', min: 6, max: 72, default: '12' },
      { type: 'color', key: 'color', label: 'Color', default: '#000000' },
    ],
    steps: [
      'Upload the PDF.',
      'Choose position, format and start number.',
      'Download the numbered PDF.',
    ],
  },
  {
    id: 'add-image-to-pdf',
    title: 'Add Image to PDF',
    description: 'Place an image (logo, signature) onto a PDF.',
    from: 'PDF+IMG',
    to: 'PDF',
    icon: 'imagePlus',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'optimize',
    multiFile: true,
    minFiles: 2,
    accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'heic'],
    options: [
      { type: 'number', key: 'x', label: 'X position (pt)', min: -2000, max: 2000, default: '50' },
      { type: 'number', key: 'y', label: 'Y position (pt)', min: -2000, max: 2000, default: '50' },
      { type: 'checkbox', key: 'everyPage', label: 'Place on every page', default: 'false' },
    ],
    steps: [
      'Upload the PDF first, then the image (JPG, PNG, WebP or HEIC).',
      'Set where the image lands on the page.',
      'Download the PDF with your image in place.',
    ],
  },
  {
    id: 'update-metadata',
    title: 'Edit Metadata',
    description: 'View and change a PDF\'s title, author and keywords.',
    from: 'PDF',
    to: 'PDF',
    icon: 'list',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'text', key: 'title', label: 'Title', placeholder: 'Document title' },
      { type: 'text', key: 'author', label: 'Author', placeholder: 'Author name' },
      { type: 'text', key: 'subject', label: 'Subject', placeholder: 'What it is about' },
      { type: 'text', key: 'keywords', label: 'Keywords', placeholder: 'comma, separated, tags' },
      { type: 'checkbox', key: 'deleteAll', label: 'Remove all metadata instead', default: 'false' },
    ],
    steps: [
      'Upload the PDF.',
      'Fill in the fields you want to set.',
      'Download the PDF with its new metadata.',
    ],
  },
  {
    id: 'replace-invert-color',
    title: 'Adjust Colors',
    description: 'Invert, recolor or high-contrast a PDF.',
    from: 'PDF',
    to: 'PDF',
    icon: 'palette',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'option',
        label: 'Mode',
        choices: [
          { value: 'FULL_INVERSION', label: 'Full inversion (dark mode)' },
          { value: 'CUSTOM_COLOR', label: 'Custom colors' },
          { value: 'HIGH_CONTRAST_COLOR', label: 'High contrast' },
          { value: 'COLOR_SPACE_CONVERSION', label: 'Color space conversion' },
        ],
        default: 'FULL_INVERSION',
      },
      { type: 'color', key: 'background', label: 'Background', default: '#ffffff', help: 'Used with "Custom colors".' },
      { type: 'color', key: 'textColor', label: 'Text', default: '#000000', help: 'Used with "Custom colors".' },
    ],
    steps: [
      'Upload the PDF.',
      'Pick a color adjustment mode.',
      'Download the recolored PDF.',
    ],
  },
  {
    id: 'scanner-effect',
    title: 'Scanner Effect',
    description: 'Make a digital PDF look like a real scan.',
    from: 'PDF',
    to: 'PDF',
    icon: 'printer',
    color: BROWN,
    tint: BROWN_TINT,
    category: 'optimize',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'select',
        key: 'quality',
        label: 'Quality',
        choices: [
          { value: 'high', label: 'High' },
          { value: 'medium', label: 'Medium' },
          { value: 'low', label: 'Low' },
        ],
        default: 'high',
      },
      {
        type: 'select',
        key: 'colorspace',
        label: 'Colorspace',
        choices: [
          { value: 'grayscale', label: 'Grayscale' },
          { value: 'color', label: 'Color' },
        ],
        default: 'grayscale',
      },
      { type: 'checkbox', key: 'yellowish', label: 'Yellowed paper tint', default: 'false' },
      { type: 'number', key: 'border', label: 'Border (px)', min: 0, max: 200, default: '20' },
    ],
    steps: [
      'Upload the digital PDF.',
      'Choose the scan look — grain, tint, border.',
      'Download the realistic-looking scan.',
    ],
  },

  /* ------------------------------ Secure ------------------------------- */
  {
    id: 'protect-pdf',
    title: 'Protect PDF',
    description: 'Encrypt a PDF with a password so only you can open it.',
    from: 'PDF',
    to: 'PDF',
    icon: 'lock',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'password',
        key: 'password',
        label: 'Password',
        required: true,
        help: 'At least 4 characters. AES-256 encryption.',
      },
    ],
    steps: [
      'Upload the PDF to lock down.',
      'Choose a strong password.',
      'Download the encrypted PDF — it now asks for the password on open.',
    ],
  },
  {
    id: 'watermark-pdf',
    title: 'Watermark PDF',
    description: 'Stamp a custom text watermark across every page.',
    from: 'PDF',
    to: 'PDF',
    icon: 'droplet',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'text',
        key: 'text',
        label: 'Watermark text',
        placeholder: 'e.g. CONFIDENTIAL',
        required: true,
      },
      { type: 'color', key: 'color', label: 'Color', default: '#d3d3d3' },
      { type: 'number', key: 'size', label: 'Font size', min: 8, max: 96, default: '30' },
      { type: 'number', key: 'angle', label: 'Angle (°)', min: -90, max: 90, default: '45' },
      { type: 'number', key: 'opacity', label: 'Opacity', min: 0.05, max: 1, step: 0.05, default: '0.5' },
    ],
    steps: [
      'Upload the PDF to watermark.',
      'Type your watermark text and tune color, size, angle and opacity.',
      'Download the watermarked PDF.',
    ],
  },
  {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove the password from a PDF you own.',
    from: 'PDF',
    to: 'PDF',
    icon: 'unlock',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'password',
        key: 'password',
        label: 'Current password',
        required: true,
        help: 'The password the PDF is protected with.',
      },
    ],
    steps: [
      'Upload the protected PDF.',
      'Enter its current password.',
      'Download the unlocked PDF — no password anymore.',
    ],
  },
  {
    id: 'sanitize-pdf',
    title: 'Sanitize PDF',
    description: 'Strip scripts, embedded files and metadata that track you.',
    from: 'PDF',
    to: 'PDF',
    icon: 'shield',
    color: BLUE,
    tint: BLUE_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      { type: 'checkbox', key: 'removeJavaScript', label: 'Remove JavaScript', default: 'true' },
      { type: 'checkbox', key: 'removeEmbeddedFiles', label: 'Remove embedded files', default: 'true' },
      { type: 'checkbox', key: 'removeXMPMetadata', label: 'Remove XMP metadata', default: 'true' },
      { type: 'checkbox', key: 'removeMetadata', label: 'Remove document metadata', default: 'true' },
      { type: 'checkbox', key: 'removeLinks', label: 'Remove links', default: 'false' },
      { type: 'checkbox', key: 'removeFonts', label: 'Remove embedded fonts', default: 'false' },
    ],
    steps: [
      'Upload the PDF to clean.',
      'Pick what to strip — scripts, attachments, metadata.',
      'Download the sanitized PDF.',
    ],
  },
  {
    id: 'auto-redact',
    title: 'Auto-Redact',
    description: 'Black out words or phrases across the whole document.',
    from: 'PDF',
    to: 'PDF',
    icon: 'eyeOff',
    color: CORAL,
    tint: CORAL_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [
      {
        type: 'text',
        key: 'listOfText',
        label: 'Text to redact',
        placeholder: 'e.g. John Smith, 555-1234',
        required: true,
        help: 'Comma-separated words or phrases.',
      },
      { type: 'checkbox', key: 'useRegex', label: 'Treat as regular expressions', default: 'false' },
      { type: 'checkbox', key: 'wholeWord', label: 'Whole words only', default: 'false' },
      { type: 'color', key: 'color', label: 'Redaction color', default: '#000000' },
    ],
    steps: [
      'Upload the PDF with sensitive content.',
      'List the words or phrases to remove.',
      'Download the redacted PDF.',
    ],
  },
  {
    id: 'remove-cert-sign',
    title: 'Remove Certificate',
    description: 'Remove digital signatures so the PDF can be edited again.',
    from: 'PDF',
    to: 'PDF',
    icon: 'x',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the signed PDF.',
      'Press Convert — signatures are stripped.',
      'Download the unsigned PDF and edit freely.',
    ],
  },
  {
    id: 'get-info-on-pdf',
    title: 'PDF Inspector',
    description: 'See everything inside a PDF — pages, size, encryption, more.',
    from: 'PDF',
    to: 'JSON',
    icon: 'info',
    color: VIOLET,
    tint: VIOLET_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF to inspect.',
      'Press Analyze — the document structure is dumped.',
      'Download the JSON report.',
    ],
  },
  {
    id: 'show-javascript',
    title: 'Show JavaScript',
    description: 'Extract any JavaScript embedded in a PDF.',
    from: 'PDF',
    to: 'TXT',
    icon: 'code',
    color: AMBER,
    tint: AMBER_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF.',
      'Press Extract — any embedded scripts are pulled out.',
      'Review the downloaded code.',
    ],
  },
  {
    id: 'unlock-pdf-forms',
    title: 'Unlock Forms',
    description: 'Make read-only PDF form fields editable again.',
    from: 'PDF',
    to: 'PDF',
    icon: 'checkSquare',
    color: GREEN,
    tint: GREEN_TINT,
    category: 'security',
    multiFile: false,
    minFiles: 1,
    accept: ['pdf'],
    options: [],
    steps: [
      'Upload the PDF with locked form fields.',
      'Press Convert — field locks are removed.',
      'Download the PDF and fill the forms.',
    ],
  },
];

export function getTool(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function toolsByCategory(category: Tool['category']): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

/** Lucide-style 24×24 stroke icons, keyed by Tool.icon. */
export const ICONS: Record<string, string> = {
  fileText:
    '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
  fileType:
    '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M9 13h6"/><path d="M9 17h3"/>',
  fileCheck:
    '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="m9 15 2 2 4-4"/>',
  fileMinus:
    '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M9 15h6"/>',
  table:
    '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M3 9h18"/><path d="M3 15h18"/><path d="M9 3v18"/><path d="M15 3v18"/>',
  sheet:
    '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M8 13h2"/><path d="M14 13h2"/><path d="M8 17h2"/><path d="M14 17h2"/>',
  combine:
    '<rect width="8" height="8" x="3" y="3" rx="1"/><rect width="8" height="8" x="13" y="13" rx="1"/><path d="M11 7h4a2 2 0 0 1 2 2v4"/>',
  scissors:
    '<circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M20 4 8.12 15.88"/><path d="M14.47 14.48 20 20"/><path d="M8.12 8.12 12 12"/>',
  minimize:
    '<path d="M8 3v3a2 2 0 0 1-2 2H3"/><path d="M21 8h-3a2 2 0 0 1-2-2V3"/><path d="M3 16h3a2 2 0 0 1 2 2v3"/><path d="M16 21v-3a2 2 0 0 1 2-2h3"/>',
  expand:
    '<path d="M15 3h6v6"/><path d="M9 21H3v-6"/><path d="M21 3l-7 7"/><path d="M3 21l7-7"/>',
  maximize:
    '<path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M21 8V5a2 2 0 0 0-2-2h-3"/><path d="M3 16v3a2 2 0 0 0 2 2h3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/>',
  image:
    '<rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>',
  imageOut:
    '<rect width="14" height="14" x="3" y="5" rx="2"/><circle cx="8" cy="10" r="1.5"/><path d="m17 12-2.5 2.5L11 11l-5 5"/><path d="M19 3v4"/><path d="M17 5h4"/>',
  imagePlus:
    '<rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/><path d="M19 2v6"/><path d="M16 5h6"/>',
  imageOff:
    '<path d="m2 2 20 20"/><path d="M9 21h10a2 2 0 0 0 2-2V9"/><path d="M3 9v10a2 2 0 0 0 2 2h1"/><path d="M5 5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v4"/>',
  lock:
    '<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
  unlock:
    '<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 9.9-1"/>',
  shield:
    '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1 1 0 0 1 1.52 0C14.5 3.8 17 5 19 5a1 1 0 0 1 1 1z"/>',
  eyeOff:
    '<path d="M9.88 9.88a3 3 0 1 0 4.24 4.24"/><path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68"/><path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61"/><path d="m2 2 20 20"/>',
  droplet:
    '<path d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z"/>',
  presentation:
    '<path d="M2 3h20"/><path d="M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3"/><path d="m7 21 5-5 5 5"/>',
  type:
    '<path d="M4 7V4h16v3"/><path d="M9 20h6"/><path d="M12 4v16"/>',
  code:
    '<path d="m16 18 6-6-6-6"/><path d="m8 6-6 6 6 6"/>',
  globe:
    '<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>',
  book:
    '<path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/>',
  bookOpen:
    '<path d="M12 7v14"/><path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z"/>',
  archive:
    '<rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/>',
  grid:
    '<rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/>',
  sections:
    '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M3 12h18"/><path d="M12 3v18"/>',
  rotate:
    '<path d="M21 12a9 9 0 1 1-3-6.7"/><path d="M21 3v6h-6"/>',
  shuffle:
    '<path d="M2 18h1.4c1.3 0 2.5-.6 3.3-1.7l6.1-8.6c.8-1.1 2-1.7 3.3-1.7H22"/><path d="m18 2 4 4-4 4"/><path d="M2 6h1.9c1.5 0 2.9.9 3.6 2.2"/><path d="M22 18h-5.9c-1.3 0-2.6-.7-3.3-1.8l-.5-.8"/><path d="m18 14 4 4-4 4"/>',
  square:
    '<rect width="18" height="18" x="3" y="3" rx="2"/>',
  weight:
    '<path d="m16 16 3-8 3 8c-.9.7-1.9 1-3 1s-2.1-.3-3-1Z"/><path d="m2 16 3-8 3 8c-.9.7-1.9 1-3 1s-2.1-.3-3-1Z"/><path d="M7 21h10"/><path d="M12 3v18"/><path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/>',
  bookmark:
    '<path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/>',
  layers:
    '<path d="m12 2 10 5-10 5L2 7Z"/><path d="m2 12 10 5 10-5"/><path d="m2 17 10 5 10-5"/>',
  flatten:
    '<path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="m6.08 10.37-3.5 1.59a1 1 0 0 0 0 1.81l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9a1 1 0 0 0 0-1.83l-3.5-1.59"/><path d="m6.08 15.87-3.5 1.59a1 1 0 0 0 0 1.81l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9a1 1 0 0 0 0-1.83l-3.5-1.59"/>',
  crop:
    '<path d="M6 2v14a2 2 0 0 0 2 2h14"/><path d="M18 22V8a2 2 0 0 0-2-2H2"/>',
  scan:
    '<path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><path d="M7 12h10"/>',
  scanText:
    '<path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><path d="M7 8h8"/><path d="M7 12h10"/><path d="M7 16h6"/>',
  printer:
    '<path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6"/><rect x="6" y="14" width="12" height="8" rx="1"/>',
  penTool:
    '<path d="m12 19 7-7 3 3-7 7-3-3z"/><path d="m18 13-1.5-7.5L2 2l3.5 14.5L13 18l5-5z"/><path d="m2 2 7.586 7.586"/><circle cx="11" cy="11" r="2"/>',
  wrench:
    '<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>',
  eraser:
    '<path d="m7 21-4.3-4.3c-1-1-1-2.5 0-3.4l9.6-9.6c1-1 2.5-1 3.4 0l5.6 5.6c1 1 1 2.5 0 3.4L13 21"/><path d="M22 21H7"/><path d="m5 11 9 9"/>',
  sparkle:
    '<path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9L12 3z"/><path d="M19 15l.9 2.1L22 18l-2.1.9L19 21l-.9-2.1L16 18l2.1-.9L19 15z"/>',
  stamp:
    '<path d="M5 22h14"/><path d="M19.27 13.73A2.5 2.5 0 0 0 17.5 13h-11A2.5 2.5 0 0 0 4 15.5V17a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-1.5c0-.66-.26-1.3-.73-1.77Z"/><path d="M14 13V8.5C14 7 15 7 15 5a3 3 0 0 0-6 0c0 2 1 2 1 3.5V13"/>',
  hash:
    '<path d="M4 9h16"/><path d="M4 15h16"/><path d="M10 3 8 21"/><path d="M16 3l-2 18"/>',
  list:
    '<path d="M8 6h13"/><path d="M8 12h13"/><path d="M8 18h13"/><path d="M3 6h.01"/><path d="M3 12h.01"/><path d="M3 18h.01"/>',
  palette:
    '<circle cx="13.5" cy="6.5" r=".5"/><circle cx="17.5" cy="10.5" r=".5"/><circle cx="8.5" cy="7.5" r=".5"/><circle cx="6.5" cy="12.5" r=".5"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"/>',
  checkSquare:
    '<path d="m9 11 3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>',
  info:
    '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>',
  x:
    '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
  google:
    '<path d="M21.35 11.1h-9.17v2.73h6.51c-.33 3.81-3.5 5.44-6.5 5.44C8.36 19.27 5 16.25 5 12c0-4.1 3.2-7.27 7.2-7.27 3.09 0 4.9 1.97 4.9 1.97L19 4.72S16.56 2 12.1 2C6.42 2 2.03 6.8 2.03 12c0 5.05 4.13 10 10.22 10c5.35 0 9.25-3.67 9.25-9.09c0-1.15-.15-1.81-.15-1.81"/>',
};
